### PR TITLE
Migrate DC-0 CHLAT to NERSC

### PR DESCRIPTION
**Pull request by zonca**
- documentation about nersc guest collection
- script to point DC0 to NERSC
- point globus files to NERSC only for CHLAT

### CODE REVIEW

**Comment by zonca** [comment]
created a simple script to replace urls pointing to UCSD with urls pointing to NERSC

**Comment by zonca** [comment]
Now I am copying the DC-0 data from UCSD to NERSC, this way I also get the `manifest.json` files.

**Comment by rpwagner** [comment]
@zonca should I have access to the data at NERSC? I'm just testing the links to start.

**Comment by zonca** [comment]
data is still in transfer.
the data is accessible by the CMB-S4 group on globus

**Comment by rpwagner** [comment]
Hmm. I'm not a member of that Globus group. Wasn't that automated? Not sure if I need to be added to something within CMB-S4 or if it's an issue with my Globus identities.

**Pull request merged**
